version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "skillsync-backend"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
